//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkClient.Bar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:fdc:cheddarmonk.org:2017:Demo", ConfigurationName="Bar.IDemoService")]
    public interface IDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fdc:cheddarmonk.org:2017:Demo/IDemoService/Reverse", ReplyAction="urn:fdc:cheddarmonk.org:2017:Demo/IDemoService/ReverseResponse")]
        string Reverse(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fdc:cheddarmonk.org:2017:Demo/IDemoService/Reverse", ReplyAction="urn:fdc:cheddarmonk.org:2017:Demo/IDemoService/ReverseResponse")]
        System.Threading.Tasks.Task<string> ReverseAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoServiceChannel : FrameworkClient.Bar.IDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoServiceClient : System.ServiceModel.ClientBase<FrameworkClient.Bar.IDemoService>, FrameworkClient.Bar.IDemoService {
        
        public DemoServiceClient() {
        }
        
        public DemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Reverse(string str) {
            return base.Channel.Reverse(str);
        }
        
        public System.Threading.Tasks.Task<string> ReverseAsync(string str) {
            return base.Channel.ReverseAsync(str);
        }
    }
}
